# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: bigflyのblog
subtitle: ''
description: ''
keywords:
author: bigfly
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://bigflya.top
permalink:  :abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# 配置百度链接主动推送
baidu_url_submit:
  count: 10 	# 表示提交最新的10个链接
  host: bigflya.top 	# 在百度站长平台中注册的域名
  token: qBQ3wNyxRck1xdx1 	# 网站秘钥 
  path: baidu_urls.txt 		# 在本地存储新url的文件名


# url优化插件
abbrlink:
  alg: crc32  #算法，支持crc16(默认) 和crc32，crc16的url比较短
  rep: hex    #进制 dec(十进制，默认) 和hex（十六进制）

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false

post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
# post_asset_folder: false  #change
relative_link: false
future: true


highlight:
  enable: true
  auto_detect: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
  exclude_languages:
    - example
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ''

  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 8
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 16
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:


      
# hexo-neat
neat_enable: true
neat_html:
  enable: true
  exclude:  
neat_css:
  enable: true
  exclude:
    - '*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js' 
    
    
    
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: pure

# Deployment
#deploy:
#  tpye: netlify
#  token: 2SZD3lSU5j7ZyzyfaPJKiuIb-MM-XPq3pDNIc2cKXGA
#  site_id: 9c4a6a2c-5339-4a6b-90fa-f9ec054c0d17
  
deploy:
  - type: git
    repository: https://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@github.com/bigflya/bigflya.github.io
    branch: master
  - type: baidu_url_submitter
## Docs: https://hexo.io/docs/one-command-deployment

